### ISSUE TITLE
Reference could not be resolved: ./params.json

### ISSUE THREAD

**Issue by dvh** [mimarec/swagger-doc-viewer#2]
I can't get the `$ref` to work no matter what I try. You README says "The base path is used to indicate the static folder containing references to the main Swagger file.", is this the `basePath` property of the spec? Unfortunately I can't find an example in the screenshots. Great extension by the way!

**Comment by mimarec** [comment]
Hi! See you a example on my github [PSD2 Example](https://github.com/mimarec/psd2-api-payments).

By the way, update to new version, for correct working on Windows. If the example isn't is useful to you, contact me again.

Thanks for feedback!!!!

**Comment by dvh** [comment]
Your example raises the error `Reference could not be resolved: ./definitions.yaml`. I didn't find any updates via VSC, so I also tried manually installing version `1.0.3`. Still no success unfortunately. By the way, also in your PSD2 example, what do you mean with "The base path is used to indicate the static folder containing references to the main Swagger file."? The `basePath` in your example is just `/payments`?

FYI: I'm working with Windows 10 Pro.

**Comment by mimarec** [comment]
Please update extension and try again.

**Comment by dvh** [comment]
Yes, it works now! Great!
